# Generated by Django 4.1 on 2023-06-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
