# Generated by Django 4.1 on 2023-06-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_alter_task_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration_of_project',
        ),
    ]
